CREATE DATABASE commentron;
CREATE DATABASE social;
CREATE USER 'lbry-rw'@'localhost' IDENTIFIED BY 'lbry';
CREATE USER 'lbry-rw'@'%' IDENTIFIED BY 'lbry';
CREATE USER 'lbry-ro'@'localhost' IDENTIFIED BY 'lbry';
CREATE USER 'lbry-ro'@'%' IDENTIFIED BY 'lbry';
GRANT ALL ON commentron.* TO 'lbry-rw'@'localhost';
GRANT ALL ON commentron.* TO 'lbry-rw'@'%';
GRANT SELECT ON commentron.* TO 'lbry-ro'@'localhost';
GRANT SELECT ON commentron.* TO 'lbry-ro'@'%';
GRANT ALL ON social.* TO 'lbry-rw'@'localhost';
GRANT ALL ON social.* TO 'lbry-rw'@'%';
